import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'
 
export default function Home() {
 
 const [email,setEmail]=useState('')
 const SendMail = async (e)=>{
   e.preventDefault();
console.log('call')
 }
 
 return (
    import Head from 'next/head'
    import styles from '../styles/Home.module.css'
    import { useState } from 'react'
    import axios from 'axios'
     
    export default function Home() {
     
     const [email,setEmail]=useState('')
     const SendMail = async (e)=>{
       e.preventDefault();
    console.log('call')
     }
     
     return (
       <div className={styles.container}>
         <Head>
           <title>Create Next App</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
         </Head>
        
     
         <main className={styles.main}>
           <form>
          <input type="email" placeholder="Enter Mail" required value={email} onChange={(e)=>setEmail(e.target.value)}></input>
          <button  onClick={{SendMail}}   > Send</button>
            </form>
         </main>
       </div>
     )
    }
 )
}